### ISSUE TITLE
Dlls are missing

### ISSUE THREAD

**Issue by sateeshmunagala** [telerik/document-processing-sdk#1]
Hi 

I downloaded the project and found missing dll's

You should at least provide  trail dll's with the examples.

Thanks

**Comment by bsivanov** [comment]
You are right, there is no info describing from where to download the missing binaries. Telerik Document Processing is currently distributes as free addition to other paid products, e.g. [UI for ASP.NET MVC](https://www.telerik.com/aspnet-mvc), [UI for ASP.NET AJAX](https://www.telerik.com/products/aspnet-ajax.aspx), [UI for WPF](https://www.telerik.com/products/wpf/overview.aspx), [UI for WinForms](https://www.telerik.com/products/winforms.aspx), so downloading a trial for any of them should provide you with the libraries.

@TanyaDimitrova, do you think we should include this info somewhere?

**Comment by TanyaDimitrova** [comment]
I added the information to the readme file of the repository.
